version: '3.8'
services:
  finance-nextjs:
    image: finance-nextjs-app:${APP_VERSION:-latest}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - API_URL=${API_URL:-/}
    ports:
      - '80:80'
    
