import Head from "next/head";
import Link from "next/link";
import { Button, Col, Row, Statistic, List, Avatar, message } from "antd";

import VirtualList from "rc-virtual-list";

import { useEffect, useState } from "react";

// const fakeDataUrl =
//   "https://randomuser.me/api/?results=20&inc=name,gender,email,nat,picture&noinfo";

const ContainerHeight = 400;
export default function Index() {

  const [data, setData] = useState([]);
  // const appendData = () => {
  //   fetch(fakeDataUrl)
  //     .then((res) => res.json())
  //     .then((body) => {
  //       setData(data.concat(body.results));
  //       message.success(`${body.results.length} more items loaded!`);
  //     });
  // };
  // useEffect(() => {
  //   appendData();
  // }, []);
  const onScroll = (e) => {
    //   if (
    //     e.currentTarget.scrollHeight - e.currentTarget.scrollTop ===
    //     ContainerHeight
    //   ) {
    //     appendData();
    //   }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/">index</Link>
        <br />
        <Link href="/history">history</Link>
        <br />
        <Link href="/sign-in">sign-in</Link>
        <br />
        <Link href="/sign-up">sign-up</Link>
        <br />
      </div>
      <Row gutter={16}>
        <Col span={12}>
          <Statistic title="Active Users" value={112893} />
        </Col>
        <Col span={12}>
          <Statistic
            title="Account Balance (CNY)"
            value={112893}
            precision={2}
          />
          <Button style={{ marginTop: 16 }} type="primary">
            Recharge
          </Button>
        </Col>
      </Row>
      <List>
        <VirtualList
          data={data}
          height={ContainerHeight}
          itemHeight={47}
          itemKey="email"
          onScroll={onScroll}>
          {([data]) => (
            <List.Item key={item.email}>
              <List.Item.Meta
                title={<a href="https://ant.design">{item.email}</a>}
                description={item.email}
              />
              <div>Content</div>
            </List.Item>
          )}
        </VirtualList>
      </List>
    </>
  );
};
